#include "buy.h"

Buy::Buy(QWidget *parent)
    : User(parent)
{
    this->resize(1100, 800);
    widget = new QWidget(this);
    widget->setObjectName(QStringLiteral("widget"));
    widget->setGeometry(QRect(10, 0, 1091, 801));
    verticalLayout = new QVBoxLayout(widget);
    verticalLayout->setSpacing(6);
    verticalLayout->setContentsMargins(11, 11, 11, 11);
    verticalLayout->setObjectName(QStringLiteral("verticalLayout"));
    verticalLayout->setContentsMargins(0, 0, 0, 0);
    verticalSpacer_5 = new QSpacerItem(20, 20, QSizePolicy::Minimum, QSizePolicy::Fixed);
    verticalLayout->addItem(verticalSpacer_5);
    horizontalLayout = new QHBoxLayout();
    horizontalLayout->setSpacing(6);
    horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
    horizontalSpacer_5 = new QSpacerItem(40, 20, QSizePolicy::Fixed, QSizePolicy::Minimum);
    horizontalLayout->addItem(horizontalSpacer_5);
    label = new QLabel(widget);
    label->setObjectName(QStringLiteral("label"));
    QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Minimum);
    sizePolicy.setHorizontalStretch(0);
    sizePolicy.setVerticalStretch(0);
    sizePolicy.setHeightForWidth(label->sizePolicy().hasHeightForWidth());
    label->setSizePolicy(sizePolicy);
    QFont font;
    font.setPointSize(16);
    label->setFont(font);
    horizontalLayout->addWidget(label);
    horizontalSpacer = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
    horizontalLayout->addItem(horizontalSpacer);
    label_3 = new QLabel(widget);
    label_3->setObjectName(QStringLiteral("label_3"));
    sizePolicy.setHeightForWidth(label_3->sizePolicy().hasHeightForWidth());
    label_3->setSizePolicy(sizePolicy);
    label_3->setFont(font);
    horizontalLayout->addWidget(label_3);
    horizontalSpacer_3 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
    horizontalLayout->addItem(horizontalSpacer_3);
    label_4 = new QLabel(widget);
    label_4->setObjectName(QStringLiteral("label_4"));
    sizePolicy.setHeightForWidth(label_4->sizePolicy().hasHeightForWidth());
    label_4->setSizePolicy(sizePolicy);
    label_4->setFont(font);
    horizontalLayout->addWidget(label_4);
    horizontalSpacer_4 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
    horizontalLayout->addItem(horizontalSpacer_4);
    label_2 = new QLabel(widget);
    label_2->setObjectName(QStringLiteral("label_2"));
    sizePolicy.setHeightForWidth(label_2->sizePolicy().hasHeightForWidth());
    label_2->setSizePolicy(sizePolicy);
    label_2->setFont(font);
    horizontalLayout->addWidget(label_2);
    horizontalSpacer_2 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
    horizontalLayout->addItem(horizontalSpacer_2);
    label_5 = new QLabel(widget);
    label_5->setObjectName(QStringLiteral("label_5"));
    sizePolicy.setHeightForWidth(label_5->sizePolicy().hasHeightForWidth());
    label_5->setSizePolicy(sizePolicy);
    label_5->setFont(font);
    horizontalLayout->addWidget(label_5);
    horizontalSpacer_6 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
    horizontalLayout->addItem(horizontalSpacer_6);
    verticalLayout->addLayout(horizontalLayout);
    verticalSpacer = new QSpacerItem(20, 20, QSizePolicy::Minimum, QSizePolicy::Fixed);
    verticalLayout->addItem(verticalSpacer);
    horizontalLayout_2 = new QHBoxLayout();
    horizontalLayout_2->setSpacing(6);
    horizontalLayout_2->setObjectName(QStringLiteral("horizontalLayout_2"));
    horizontalSpacer_10 = new QSpacerItem(200, 20, QSizePolicy::Fixed, QSizePolicy::Minimum);
    horizontalLayout_2->addItem(horizontalSpacer_10);
    label_7 = new QLabel(widget);
    label_7->setObjectName(QStringLiteral("label_7"));
    sizePolicy.setHeightForWidth(label_7->sizePolicy().hasHeightForWidth());
    label_7->setSizePolicy(sizePolicy);
    label_7->setFont(font);
    horizontalLayout_2->addWidget(label_7);
    horizontalSpacer_7 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
    horizontalLayout_2->addItem(horizontalSpacer_7);
    label_6 = new QLabel(widget);
    label_6->setObjectName(QStringLiteral("label_6"));
    sizePolicy.setHeightForWidth(label_6->sizePolicy().hasHeightForWidth());
    label_6->setSizePolicy(sizePolicy);
    label_6->setFont(font);
    horizontalLayout_2->addWidget(label_6);
    horizontalSpacer_8 = new QSpacerItem(300, 20, QSizePolicy::Fixed, QSizePolicy::Minimum);
    horizontalLayout_2->addItem(horizontalSpacer_8);
    verticalLayout->addLayout(horizontalLayout_2);
    verticalSpacer_2 = new QSpacerItem(20, 20, QSizePolicy::Minimum, QSizePolicy::Fixed);
    verticalLayout->addItem(verticalSpacer_2);
    horizontalLayout_6 = new QHBoxLayout();
    horizontalLayout_6->setSpacing(6);
    horizontalLayout_6->setObjectName(QStringLiteral("horizontalLayout_6"));
    horizontalSpacer_11 = new QSpacerItem(200, 20, QSizePolicy::Fixed, QSizePolicy::Minimum);
    horizontalLayout_6->addItem(horizontalSpacer_11);
    label_9 = new QLabel(widget);
    label_9->setObjectName(QStringLiteral("label_9"));
    sizePolicy.setHeightForWidth(label_9->sizePolicy().hasHeightForWidth());
    label_9->setSizePolicy(sizePolicy);
    label_9->setFont(font);
    horizontalLayout_6->addWidget(label_9);
    horizontalSpacer_18 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
    horizontalLayout_6->addItem(horizontalSpacer_18);
    label_8 = new QLabel(widget);
    label_8->setObjectName(QStringLiteral("label_8"));
    sizePolicy.setHeightForWidth(label_8->sizePolicy().hasHeightForWidth());
    label_8->setSizePolicy(sizePolicy);
    label_8->setFont(font);
    horizontalLayout_6->addWidget(label_8);
    horizontalSpacer_9 = new QSpacerItem(300, 20, QSizePolicy::Fixed, QSizePolicy::Minimum);
    horizontalLayout_6->addItem(horizontalSpacer_9);
    verticalLayout->addLayout(horizontalLayout_6);
    verticalSpacer_7 = new QSpacerItem(20, 20, QSizePolicy::Minimum, QSizePolicy::Fixed);
    verticalLayout->addItem(verticalSpacer_7);
    horizontalLayout_3 = new QHBoxLayout();
    horizontalLayout_3->setSpacing(6);
    horizontalLayout_3->setObjectName(QStringLiteral("horizontalLayout_3"));
    horizontalSpacer_13 = new QSpacerItem(40, 20, QSizePolicy::Fixed, QSizePolicy::Minimum);
    horizontalLayout_3->addItem(horizontalSpacer_13);
    label_10 = new QLabel(widget);
    label_10->setObjectName(QStringLiteral("label_10"));
    sizePolicy.setHeightForWidth(label_10->sizePolicy().hasHeightForWidth());
    label_10->setSizePolicy(sizePolicy);
    label_10->setFont(font);
    horizontalLayout_3->addWidget(label_10);
    horizontalSpacer_12 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
    horizontalLayout_3->addItem(horizontalSpacer_12);
    verticalLayout->addLayout(horizontalLayout_3);
    verticalSpacer_3 = new QSpacerItem(20, 20, QSizePolicy::Minimum, QSizePolicy::Minimum);
    verticalLayout->addItem(verticalSpacer_3);
    horizontalLayout_4 = new QHBoxLayout();
    horizontalLayout_4->setSpacing(6);
    horizontalLayout_4->setObjectName(QStringLiteral("horizontalLayout_4"));
    horizontalSpacer_16 = new QSpacerItem(125, 40, QSizePolicy::Fixed, QSizePolicy::Minimum);
    horizontalLayout_4->addItem(horizontalSpacer_16);
    tableWidget = new QTableWidget(widget);
    if (tableWidget->columnCount() < 3)
        tableWidget->setColumnCount(3);
    QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
    tableWidget->setHorizontalHeaderItem(0, __qtablewidgetitem);
    QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
    tableWidget->setHorizontalHeaderItem(1, __qtablewidgetitem1);
    QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
    tableWidget->setHorizontalHeaderItem(2, __qtablewidgetitem2);
    if (tableWidget->rowCount() < 3)
        tableWidget->setRowCount(3);
    QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
    tableWidget->setVerticalHeaderItem(0, __qtablewidgetitem3);
    QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
    tableWidget->setVerticalHeaderItem(1, __qtablewidgetitem4);
    QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
    tableWidget->setVerticalHeaderItem(2, __qtablewidgetitem5);
    tableWidget->setObjectName(QStringLiteral("tableWidget"));
    QSizePolicy sizePolicy1(QSizePolicy::Ignored, QSizePolicy::MinimumExpanding);
    sizePolicy1.setHorizontalStretch(0);
    sizePolicy1.setVerticalStretch(0);
    sizePolicy1.setHeightForWidth(tableWidget->sizePolicy().hasHeightForWidth());
    tableWidget->setSizePolicy(sizePolicy1);
    tableWidget->setFont(font);
    tableWidget->setGridStyle(Qt::SolidLine);
    tableWidget->setCornerButtonEnabled(true);
    tableWidget->horizontalHeader()->setVisible(true);
    tableWidget->horizontalHeader()->setDefaultSectionSize(200);
    tableWidget->horizontalHeader()->setHighlightSections(true);
    tableWidget->verticalHeader()->setVisible(true);
    tableWidget->verticalHeader()->setDefaultSectionSize(100);
    tableWidget->verticalHeader()->setHighlightSections(true);
    tableWidget->verticalHeader()->setProperty("showSortIndicator", QVariant(false));
    horizontalLayout_4->addWidget(tableWidget);
    horizontalSpacer_17 = new QSpacerItem(222, 40, QSizePolicy::Fixed, QSizePolicy::Minimum);
    horizontalLayout_4->addItem(horizontalSpacer_17);
    verticalLayout->addLayout(horizontalLayout_4);
    verticalSpacer_4 = new QSpacerItem(20, 100, QSizePolicy::Minimum, QSizePolicy::Fixed);
    verticalLayout->addItem(verticalSpacer_4);
    horizontalLayout_5 = new QHBoxLayout();
    horizontalLayout_5->setSpacing(6);
    horizontalLayout_5->setObjectName(QStringLiteral("horizontalLayout_5"));
    horizontalSpacer_14 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
    horizontalLayout_5->addItem(horizontalSpacer_14);
    horizontalSpacer_15 = new QSpacerItem(40, 20, QSizePolicy::Expanding, QSizePolicy::Minimum);
    horizontalLayout_5->addItem(horizontalSpacer_15);
    buttonBox = new QDialogButtonBox(widget);
    buttonBox->setObjectName(QStringLiteral("buttonBox"));
    buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);
    horizontalLayout_5->addWidget(buttonBox);
    horizontalSpacer_19 = new QSpacerItem(200, 20, QSizePolicy::Fixed, QSizePolicy::Minimum);
    horizontalLayout_5->addItem(horizontalSpacer_19);
    verticalLayout->addLayout(horizontalLayout_5);
    verticalSpacer_6 = new QSpacerItem(20, 20, QSizePolicy::Minimum, QSizePolicy::Fixed);
    verticalLayout->addItem(verticalSpacer_6);
    this->setWindowTitle(QApplication::translate("Buy", "Buy", 0));
    label->setText(QApplication::translate("Buy", "1024", 0));
    label_3->setText(QApplication::translate("Buy", "From", 0));
    label_4->setText(QApplication::translate("Buy", "ChangChun", 0));
    label_2->setText(QApplication::translate("Buy", "To", 0));
    label_5->setText(QApplication::translate("Buy", "ChangChun", 0));
    label_7->setText(QApplication::translate("Buy", "Departuarure Time", 0));
    label_6->setText(QApplication::translate("Buy", "2016-8-25 18:22:12", 0));
    label_9->setText(QApplication::translate("Buy", "Arrival Time", 0));
    label_8->setText(QApplication::translate("Buy", "2016-8-25 18:22:12", 0));
    label_10->setText(QApplication::translate("Buy", "Contacts", 0));
    QTableWidgetItem *___qtablewidgetitem = tableWidget->horizontalHeaderItem(0);
    ___qtablewidgetitem->setText(QApplication::translate("Buy", "Name", 0));
    QTableWidgetItem *___qtablewidgetitem1 = tableWidget->horizontalHeaderItem(1);
    ___qtablewidgetitem1->setText(QApplication::translate("Buy", "ID", 0));
    QTableWidgetItem *___qtablewidgetitem2 = tableWidget->horizontalHeaderItem(2);
    ___qtablewidgetitem2->setText(QApplication::translate("Buy", "Notes", 0));
    QTableWidgetItem *___qtablewidgetitem3 = tableWidget->verticalHeaderItem(0);
    ___qtablewidgetitem3->setText(QApplication::translate("Buy", "Person 1", 0));
    QTableWidgetItem *___qtablewidgetitem4 = tableWidget->verticalHeaderItem(1);
    ___qtablewidgetitem4->setText(QApplication::translate("Buy", "Person 2", 0));
    QTableWidgetItem *___qtablewidgetitem5 = tableWidget->verticalHeaderItem(2);
    ___qtablewidgetitem5->setText(QApplication::translate("Buy", "Person 3", 0));
    tableWidget->horizontalHeader()->setFont(font);
}

Buy::~Buy()
{

}
